seed=22
dataset='ultrafb_bin'
basemodel='gemma2-2b'
######sft############
# train
# rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name sft --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project sft --global_batch_size 64 --learning_rate 5e-6 --max_grad_norm 10.0 --sample_ontest --n_epoch 2 

# eval
# rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name sft --model_name gemma2-2b  --dataset ultrafb_bin  --global_batch_size 128  --eval_only --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf --sample_ontest 

#######reward########
# #train
# rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name reward --model_name gemma2-2b  --dataset ultrafb_bin --wandb_enabled --wandb_project reward --global_batch_size 32 --learning_rate 5e-6 --max_grad_norm 5.0 --exp_name reward_gemma2-2b_ultrafb_bin --n_epoch 1 
# rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name reward --model_name gemma2-2b  --dataset ultrafb_bin --wandb_enabled --wandb_project reward --global_batch_size 24 --learning_rate 5e-6 --reward_reg   --max_grad_norm 5.0 --exp_name reward_gemma2-2b_ultrafb_bin_reg --n_epoch 1 
# For WARM
# rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name reward --model_name gemma2-2b  --dataset ultrafb_bin --wandb_enabled --wandb_project reward --global_batch_size 32 --learning_rate 7e-6 --max_grad_norm 5.0 --exp_name reward_gemma2-2b_ultrafb_bin_M1 --seed 23 --n_examples 9700
# rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name reward --model_name gemma2-2b  --dataset ultrafb_bin --wandb_enabled --wandb_project reward --global_batch_size 32 --learning_rate 6e-6 --max_grad_norm 5.0 --exp_name reward_gemma2-2b_ultrafb_bin_M2 --seed 24 --n_examples 14300
# rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name reward --model_name gemma2-2b  --dataset ultrafb_bin --wandb_enabled --wandb_project reward --global_batch_size 24 --learning_rate 5e-6 --max_grad_norm 5.0 --exp_name reward_gemma2-2b_ultrafb_bin_M3 --seed 25 --n_examples 19200
# rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name reward --model_name gemma2-2b  --dataset ultrafb_bin --wandb_enabled --wandb_project reward --global_batch_size 24 --learning_rate 4e-6 --max_grad_norm 5.0 --exp_name reward_gemma2-2b_ultrafb_bin_M4 --seed 26 --n_examples 24000
# rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name reward --model_name gemma2-2b  --dataset ultrafb_bin --wandb_enabled --wandb_project reward --global_batch_size 24 --learning_rate 3e-6 --max_grad_norm 5.0 --exp_name reward_gemma2-2b_ultrafb_bin_M5 --seed 27 --n_examples 28800
# rlaunch --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- python3 model_merge.py --base_model_name gemma2-2b --dataset_name ultrafb_bin

# For ODIN
# rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name reward_odin --model_name gemma2-2b  --dataset ultrafb_bin --wandb_enabled --wandb_project reward --global_batch_size 24 --learning_rate 5e-6 --reward_odin --max_grad_norm 5.0 --exp_name reward_gemma2-2b_ultrafb_bin_odin --n_epoch 1 


#############generate references and calculate reward################
# rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name gen_refs --model_name gemma2-2b --dataset ultrafb_bin --global_batch_size 32 --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf --reward_path /data/models/reward_gemma2-2b_ultrafb_bin --reward_tag latest_hf --n_epoch 1 
# python utils.py

#Mitigate Reward Hacking
###PPO
# rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ppo --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project ppo --global_batch_size 40 --learning_rate 3e-7  --critic_lr 5e-6 --max_grad_norm 5.0  --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_gemma2-2b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_gemma2-2b_ultrafb_bin     --reward_tag latest_hf  --critic_path /data/models/reward_gemma2-2b_ultrafb_bin         --critic_tag latest_hf  --exp_name ppo_gemma2-2b_ultrafb_bin_vanilla  --save_ckps all --n_epochs 1 
# rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ppo --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project ppo --global_batch_size 40 --learning_rate 3e-7  --critic_lr 5e-6 --max_grad_norm 5.0  --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_gemma2-2b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_gemma2-2b_ultrafb_bin_WARM    --reward_tag latest_hf  --critic_path /data/models/reward_gemma2-2b_ultrafb_bin_WARM    --critic_tag latest_hf  --exp_name ppo_gemma2-2b_ultrafb_bin_WARM  --save_ckps all --n_epochs 1 
# rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ppo --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project ppo --global_batch_size 40 --learning_rate 3e-7  --critic_lr 5e-6 --max_grad_norm 5.0  --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_gemma2-2b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_gemma2-2b_ultrafb_bin_odin    --reward_tag latest_hf  --critic_path /data/models/reward_gemma2-2b_ultrafb_bin_odin    --critic_tag latest_hf  --reward_odin --exp_name ppo_gemma2-2b_ultrafb_bin_ODIN  --save_ckps all --n_epochs 1 
# rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ppo --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project ppo --global_batch_size 40 --learning_rate 3e-7  --critic_lr 5e-6 --max_grad_norm 5.0  --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_gemma2-2b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_gemma2-2b_ultrafb_bin_reg --reward_tag latest_hf  --critic_path /data/models/reward_gemma2-2b_ultrafb_bin_reg     --critic_tag latest_hf  --exp_name ppo_gemma2-2b_ultrafb_bin_reg   --save_ckps all --n_epochs 1 
# rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ppo --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project ppo --global_batch_size 40 --learning_rate 3e-7  --critic_lr 5e-6 --max_grad_norm 5.0  --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_gemma2-2b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_gemma2-2b_ultrafb_bin     --reward_tag latest_hf  --critic_path /data/models/reward_gemma2-2b_ultrafb_bin         --critic_tag latest_hf  --reward_meanstd  --exp_name ppo_gemma2-2b_ultrafb_bin_meanstd  --save_ckps all  --n_epochs 1 
# rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ppo --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project ppo --global_batch_size 40 --learning_rate 3e-7  --critic_lr 5e-6 --max_grad_norm 5.0  --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_gemma2-2b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_gemma2-2b_ultrafb_bin     --reward_tag latest_hf  --critic_path /data/models/reward_gemma2-2b_ultrafb_bin         --critic_tag latest_hf  --reward_clipping  --exp_name ppo_gemma2-2b_ultrafb_bin_clip    --save_ckps all --n_epochs 1
# rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ppo --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project ppo --global_batch_size 40 --learning_rate 3e-7  --critic_lr 5e-6 --max_grad_norm 5.0  --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_gemma2-2b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_gemma2-2b_ultrafb_bin     --reward_tag latest_hf  --critic_path /data/models/reward_gemma2-2b_ultrafb_bin         --critic_tag latest_hf  --reward_minmax  --exp_name ppo_gemma2-2b_ultrafb_bin_minmax    --save_ckps all --n_epochs 1
# rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ppo --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project ppo --global_batch_size 40 --learning_rate 3e-7  --critic_lr 5e-6 --max_grad_norm 5.0  --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_gemma2-2b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_gemma2-2b_ultrafb_bin     --reward_tag latest_hf  --critic_path /data/models/reward_gemma2-2b_ultrafb_bin         --critic_tag latest_hf  --reward_lsc  --reward_relative --exp_name ppo_gemma2-2b_ultrafb_bin_lsc   --save_ckps all --n_epochs 1 
# rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ppo --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project ppo --global_batch_size 40 --learning_rate 3e-7  --critic_lr 5e-6 --max_grad_norm 5.0  --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_gemma2-2b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_gemma2-2b_ultrafb_bin     --reward_tag latest_hf  --critic_path /data/models/reward_gemma2-2b_ultrafb_bin         --critic_tag latest_hf  --reward_sigmoid   --reward_relative  --exp_name ppo_gemma2-2b_ultrafb_bin_PAR   --save_ckps all --n_epochs 1 
# Evaluate on benchmark

###GRPO
rlaunch --gpu=8 --cpu=100 --replica=2 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name grpo --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project grpo --global_batch_size 16 --learning_rate 3e-7   --max_grad_norm 5.0  --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_gemma2-2b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_gemma2-2b_ultrafb_bin     --reward_tag latest_hf --exp_name grpo_gemma2-2b_ultrafb_bin_vanilla  --no_save_latest --n_epochs 2
rlaunch --gpu=8 --cpu=100 --replica=2 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name grpo --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project grpo --global_batch_size 16 --learning_rate 3e-7  --max_grad_norm 5.0  --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_gemma2-2b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_gemma2-2b_ultrafb_bin_WARM    --reward_tag latest_hf  --exp_name grpo_gemma2-2b_ultrafb_bin_WARM   --no_save_latest --n_epochs 2
rlaunch --gpu=8 --cpu=100 --replica=2 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name grpo --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project grpo --global_batch_size 16 --learning_rate 3e-7  --max_grad_norm 5.0  --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_gemma2-2b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_gemma2-2b_ultrafb_bin_odin    --reward_tag latest_hf  --reward_odin --exp_name grpo_gemma2-2b_ultrafb_bin_ODIN   --no_save_latest --n_epochs 2
rlaunch --gpu=8 --cpu=100 --replica=2 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name grpo --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project grpo --global_batch_size 16 --learning_rate 3e-7  --max_grad_norm 5.0  --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_gemma2-2b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_gemma2-2b_ultrafb_bin_reg --reward_tag latest_hf   --exp_name grpo_gemma2-2b_ultrafb_bin_reg  --no_save_latest --n_epochs 2
rlaunch --gpu=8 --cpu=100 --replica=2 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name grpo --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project grpo --global_batch_size 16 --learning_rate 3e-7   --max_grad_norm 5.0  --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_gemma2-2b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_gemma2-2b_ultrafb_bin     --reward_tag latest_hf --reward_meanstd  --exp_name grpo_gemma2-2b_ultrafb_bin_meanstd --no_save_latest --n_epochs 2
rlaunch --gpu=8 --cpu=100 --replica=2 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name grpo --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project grpo --global_batch_size 16 --learning_rate 3e-7  --max_grad_norm 5.0  --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_gemma2-2b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_gemma2-2b_ultrafb_bin     --reward_tag latest_hf  --reward_clipping  --exp_name grpo_gemma2-2b_ultrafb_bin_clip  --no_save_latest --n_epochs 2
rlaunch --gpu=8 --cpu=100 --replica=2 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name grpo --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project grpo --global_batch_size 16 --learning_rate 3e-7   --max_grad_norm 5.0  --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_gemma2-2b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_gemma2-2b_ultrafb_bin     --reward_tag latest_hf --reward_minmax  --exp_name grpo_gemma2-2b_ultrafb_bin_minmax --no_save_latest --n_epochs 2
rlaunch --gpu=8 --cpu=100 --replica=2 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name grpo --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project grpo --global_batch_size 16 --learning_rate 3e-7  --max_grad_norm 5.0  --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_gemma2-2b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_gemma2-2b_ultrafb_bin     --reward_tag latest_hf  --reward_lsc  --reward_relative --exp_name grpo_gemma2-2b_ultrafb_bin_lsc  --no_save_latest --n_epochs 2
rlaunch --gpu=8 --cpu=100 --replica=2 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name grpo --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project grpo --global_batch_size 16 --learning_rate 3e-7   --max_grad_norm 5.0  --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_gemma2-2b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_gemma2-2b_ultrafb_bin     --reward_tag latest_hf --reward_sigmoid   --reward_relative  --exp_name grpo_gemma2-2b_ultrafb_bin_PAR --no_save_latest --n_epochs 2

###ReMax
# rlaunch --gpu=8 --cpu=100 --replica=2 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name remax --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project remax --global_batch_size 32 --learning_rate 3e-7   --max_grad_norm 5.0  --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf  --reward_path /data/models/reward_gemma2-2b_ultrafb_bin   --reward_tag latest_hf --exp_name remax_gemma2-2b_ultrafb_bin_vanilla  --n_epochs 1 
# rlaunch --gpu=8 --cpu=100 --replica=2 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name remax --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project remax --global_batch_size 32 --learning_rate 3e-7   --max_grad_norm 5.0  --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf  --reward_path /data/models/reward_gemma2-2b_ultrafb_bin   --reward_tag latest_hf --reward_sigmoid   --reward_relative  --exp_name remax_gemma2-2b_ultrafb_bin_PAR --n_epochs 1 
# rlaunch --gpu=8 --cpu=100 --replica=2 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name remax --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project remax --global_batch_size 32 --learning_rate 3e-7   --max_grad_norm 5.0  --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf  --reward_path /data/models/reward_gemma2-2b_ultrafb_bin   --reward_tag latest_hf --reward_minmax  --exp_name remax_gemma2-2b_ultrafb_bin_minmax --n_epochs 1 

#Data Effective
# rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ppo --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project ppo --global_batch_size 40 --learning_rate 3e-7  --critic_lr 5e-6 --max_grad_norm 5.0  --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_gemma2-2b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_gemma2-2b_ultrafb_bin     --reward_tag latest_hf  --critic_path /data/models/reward_gemma2-2b_ultrafb_bin   --critic_tag latest_hf  --reward_sigmoid  --reward_relative --reward_maxref 1  --exp_name ppo_gemma2-2b_ultrafb_bin_PARref1 --no_save_latest --n_epochs 1 
# rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ppo --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project ppo --global_batch_size 40 --learning_rate 3e-7  --critic_lr 5e-6 --max_grad_norm 5.0  --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_gemma2-2b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_gemma2-2b_ultrafb_bin     --reward_tag latest_hf  --critic_path /data/models/reward_gemma2-2b_ultrafb_bin   --critic_tag latest_hf  --reward_sigmoid  --reward_relative --reward_maxref 3  --exp_name ppo_gemma2-2b_ultrafb_bin_PARref3 --no_save_latest --n_epochs 1 
# rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ppo --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project ppo --global_batch_size 40 --learning_rate 3e-7  --critic_lr 5e-6 --max_grad_norm 5.0  --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_gemma2-2b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_gemma2-2b_ultrafb_bin     --reward_tag latest_hf  --critic_path /data/models/reward_gemma2-2b_ultrafb_bin   --critic_tag latest_hf  --reward_sigmoid  --reward_relative --reward_maxref 5  --exp_name ppo_gemma2-2b_ultrafb_bin_PARref5 --no_save_latest --n_epochs 1 
# rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ppo --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project ppo --global_batch_size 40 --learning_rate 3e-7  --critic_lr 5e-6 --max_grad_norm 5.0  --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_gemma2-2b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_gemma2-2b_ultrafb_bin     --reward_tag latest_hf  --critic_path /data/models/reward_gemma2-2b_ultrafb_bin   --critic_tag latest_hf  --reward_sigmoid  --reward_relative --reward_maxref 8  --exp_name ppo_gemma2-2b_ultrafb_bin_PARref8 --no_save_latest --n_epochs 1 

#Robust
#PAR, MINMAX, WARM
# rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ppo --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project ppo --global_batch_size 40 --learning_rate 3e-7  --critic_lr 5e-6 --max_grad_norm 5.0  --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_gemma2-2b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_gemma2-2b_ultrafb_bin     --reward_tag latest_hf  --critic_path /data/models/reward_gemma2-2b_ultrafb_bin   --critic_tag latest_hf --reward_sigmoid  --reward_relative --exp_name ppo_gemma2-2b_ultrafb_bin_PARep2 --no_save_latest --n_epochs 2 
# rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ppo --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project ppo --global_batch_size 40 --learning_rate 3e-7  --critic_lr 5e-6 --max_grad_norm 5.0  --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_gemma2-2b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_gemma2-2b_ultrafb_bin     --reward_tag latest_hf  --critic_path /data/models/reward_gemma2-2b_ultrafb_bin   --critic_tag latest_hf  --reward_minmax   --exp_name ppo_gemma2-2b_ultrafb_bin_minmaxep2 --no_save_latest --n_epochs 2 
# rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ppo --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project ppo --global_batch_size 40 --learning_rate 3e-7  --critic_lr 5e-6 --max_grad_norm 5.0  --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_gemma2-2b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_gemma2-2b_ultrafb_bin_WARM    --reward_tag latest_hf  --critic_path /data/models/reward_gemma2-2b_ultrafb_bin_WARM    --critic_tag latest_hf  --exp_name ppo_gemma2-2b_ultrafb_bin_WARMep2  --no_save_latest --n_epochs 2 

#Principle 1: Excessive Reward Leads to RH(RL reward is ideally bounded)
# rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ppo --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project ppo --global_batch_size 40 --learning_rate 3e-7  --critic_lr 5e-6 --max_grad_norm 5.0  --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_gemma2-2b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_gemma2-2b_ultrafb_bin     --reward_tag latest_hf  --critic_path /data/models/reward_gemma2-2b_ultrafb_bin   --critic_tag latest_hf  --KL_coef 0.01 --exp_name ppo_gemma2-2b_ultrafb_bin_kl0.01  --no_save_latest --n_epochs 2 
# rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ppo --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project ppo --global_batch_size 40 --learning_rate 3e-7  --critic_lr 5e-6 --max_grad_norm 5.0  --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_gemma2-2b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_gemma2-2b_ultrafb_bin     --reward_tag latest_hf  --critic_path /data/models/reward_gemma2-2b_ultrafb_bin   --critic_tag latest_hf  --KL_coef 0.02 --exp_name ppo_gemma2-2b_ultrafb_bin_kl0.02  --no_save_latest --n_epochs 2 
# rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ppo --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project ppo --global_batch_size 40 --learning_rate 3e-7  --critic_lr 5e-6 --max_grad_norm 5.0  --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_gemma2-2b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_gemma2-2b_ultrafb_bin     --reward_tag latest_hf  --critic_path /data/models/reward_gemma2-2b_ultrafb_bin   --critic_tag latest_hf  --KL_coef 0.05 --exp_name ppo_gemma2-2b_ultrafb_bin_kl0.05  --no_save_latest --n_epochs 2 
# rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ppo --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project ppo --global_batch_size 40 --learning_rate 3e-7  --critic_lr 5e-6 --max_grad_norm 5.0  --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_gemma2-2b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_gemma2-2b_ultrafb_bin     --reward_tag latest_hf  --critic_path /data/models/reward_gemma2-2b_ultrafb_bin   --critic_tag latest_hf  --KL_coef 0.1  --exp_name ppo_gemma2-2b_ultrafb_bin_kl0.1   --no_save_latest --n_epochs 2 

# rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ppo --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project ppo --global_batch_size 40 --learning_rate 3e-7  --critic_lr 5e-6 --max_grad_norm 5.0  --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_gemma2-2b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_gemma2-2b_ultrafb_bin     --reward_tag latest_hf  --critic_path /data/models/reward_gemma2-2b_ultrafb_bin   --critic_tag latest_hf  --reward_ceil 5.0 --exp_name ppo_gemma2-2b_ultrafb_bin_ceil5.0 --no_save_latest --n_epochs 2 
# rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ppo --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project ppo --global_batch_size 40 --learning_rate 3e-7  --critic_lr 5e-6 --max_grad_norm 5.0  --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_gemma2-2b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_gemma2-2b_ultrafb_bin     --reward_tag latest_hf  --critic_path /data/models/reward_gemma2-2b_ultrafb_bin   --critic_tag latest_hf  --reward_ceil 4.0 --exp_name ppo_gemma2-2b_ultrafb_bin_ceil4.0 --no_save_latest --n_epochs 2 
# rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ppo --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project ppo --global_batch_size 40 --learning_rate 3e-7  --critic_lr 5e-6 --max_grad_norm 5.0  --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_gemma2-2b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_gemma2-2b_ultrafb_bin     --reward_tag latest_hf  --critic_path /data/models/reward_gemma2-2b_ultrafb_bin   --critic_tag latest_hf  --reward_ceil 3.0 --exp_name ppo_gemma2-2b_ultrafb_bin_ceil3.0 --no_save_latest --n_epochs 2 



#Principle 2: Rapid initial growth followed by gradual convergence
# rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ppo --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project ppo --global_batch_size 40 --learning_rate 3e-7  --critic_lr 5e-6 --max_grad_norm 5.0  --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_gemma2-2b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_gemma2-2b_ultrafb_bin   --reward_tag latest_hf  --critic_path /data/models/reward_gemma2-2b_ultrafb_bin     --critic_tag latest_hf  --reward_sgfc --reward_relative --exp_name ppo_gemma2-2b_ultrafb_bin_sgfc --no_save_latest --n_epochs 1 

#Principle 3: Centered Reward
# rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ppo --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project ppo --global_batch_size 40 --learning_rate 3e-7  --critic_lr 5e-6 --max_grad_norm 5.0  --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_gemma2-2b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_gemma2-2b_ultrafb_bin     --reward_tag latest_hf  --critic_path /data/models/reward_gemma2-2b_ultrafb_bin   --critic_tag latest_hf  --reward_tanh    --reward_relative --exp_name ppo_gemma2-2b_ultrafb_bin_relatanh --no_save_latest --n_epochs 1 
# rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ppo --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project ppo --global_batch_size 40 --learning_rate 3e-7  --critic_lr 5e-6 --max_grad_norm 5.0  --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_gemma2-2b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_gemma2-2b_ultrafb_bin     --reward_tag latest_hf  --critic_path /data/models/reward_gemma2-2b_ultrafb_bin   --critic_tag latest_hf  --reward_fittedpoly    --reward_relative --exp_name ppo_gemma2-2b_ultrafb_bin_relafittedpoly --no_save_latest --n_epochs 1 
# rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ppo --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project ppo --global_batch_size 40 --learning_rate 3e-7  --critic_lr 5e-6 --max_grad_norm 5.0  --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_gemma2-2b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_gemma2-2b_ultrafb_bin     --reward_tag latest_hf  --critic_path /data/models/reward_gemma2-2b_ultrafb_bin   --critic_tag latest_hf  --reward_sigmoid   --sigmoid_k 2 --reward_relative --exp_name ppo_gemma2-2b_ultrafb_bin_relasigmoidk2 --no_save_latest --n_epochs 1 
# rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ppo --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project ppo --global_batch_size 40 --learning_rate 3e-7  --critic_lr 5e-6 --max_grad_norm 5.0  --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_gemma2-2b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_gemma2-2b_ultrafb_bin     --reward_tag latest_hf  --critic_path /data/models/reward_gemma2-2b_ultrafb_bin   --critic_tag latest_hf  --reward_sigmoid   --sigmoid_k 3 --reward_relative --exp_name ppo_gemma2-2b_ultrafb_bin_relasigmoidk3 --no_save_latest --n_epochs 1 

# rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ppo --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project ppo --global_batch_size 40 --learning_rate 3e-7  --critic_lr 5e-6 --max_grad_norm 5.0  --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_gemma2-2b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_gemma2-2b_ultrafb_bin     --reward_tag latest_hf  --critic_path /data/models/reward_gemma2-2b_ultrafb_bin   --critic_tag latest_hf  --reward_tanh    --exp_name ppo_gemma2-2b_ultrafb_bin_puretanh --no_save_latest --n_epochs 1 
# rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ppo --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project ppo --global_batch_size 40 --learning_rate 3e-7  --critic_lr 5e-6 --max_grad_norm 5.0  --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_gemma2-2b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_gemma2-2b_ultrafb_bin     --reward_tag latest_hf  --critic_path /data/models/reward_gemma2-2b_ultrafb_bin   --critic_tag latest_hf  --reward_fittedpoly  --exp_name ppo_gemma2-2b_ultrafb_bin_purefittedpoly --no_save_latest --n_epochs 1 
# rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ppo --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project ppo --global_batch_size 40 --learning_rate 3e-7  --critic_lr 5e-6 --max_grad_norm 5.0  --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_gemma2-2b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_gemma2-2b_ultrafb_bin     --reward_tag latest_hf  --critic_path /data/models/reward_gemma2-2b_ultrafb_bin   --critic_tag latest_hf  --reward_sigmoid   --sigmoid_k 2  --exp_name ppo_gemma2-2b_ultrafb_bin_puresigmoidk2 --no_save_latest --n_epochs 1 
# rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ppo --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project ppo --global_batch_size 40 --learning_rate 3e-7  --critic_lr 5e-6 --max_grad_norm 5.0  --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_gemma2-2b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_gemma2-2b_ultrafb_bin     --reward_tag latest_hf  --critic_path /data/models/reward_gemma2-2b_ultrafb_bin   --critic_tag latest_hf  --reward_sigmoid   --sigmoid_k 3  --exp_name ppo_gemma2-2b_ultrafb_bin_puresigmoidk3 --no_save_latest --n_epochs 1 
# rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ppo --model_name gemma2-2b --dataset ultrafb_bin --wandb_enabled --wandb_project ppo --global_batch_size 40 --learning_rate 3e-7  --critic_lr 5e-6 --max_grad_norm 5.0  --policy_path /data/models/sft_gemma2-2b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_gemma2-2b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_gemma2-2b_ultrafb_bin   --reward_tag latest_hf  --critic_path /data/models/reward_gemma2-2b_ultrafb_bin     --critic_tag latest_hf  --reward_centered --exp_name ppo_gemma2-2b_ultrafb_bin_vanilla_centered --no_save_latest --n_epochs 1 
