seed=22
dataset='ultrafb_bin'
basemodel='llama3-8b'

######sft############
# train
rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name sft --model_name llama3-8b --dataset ultrafb_bin --wandb_enabled --wandb_project sft --global_batch_size 24 --learning_rate 5e-6 --max_grad_norm 10.0 --sample_ontest --n_epoch 2 

# eval
rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name sft --model_name llama3-8b  --dataset ultrafb_bin  --global_batch_size 128  --eval_only --policy_path /data/models/sft_llama3-8b_ultrafb_bin --policy_tag latest_hf --sample_ontest 

#######reward########
# #train
rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name reward --model_name llama3-8b  --dataset ultrafb_bin --wandb_enabled --wandb_project reward --global_batch_size 16 --learning_rate 5e-6 --max_grad_norm 5.0 --exp_name reward_llama3-8b_ultrafb_bin --n_epoch 1 
rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name reward --model_name llama3-8b  --dataset ultrafb_bin --wandb_enabled --wandb_project reward --global_batch_size 16 --learning_rate 5e-6 --reward_reg   --max_grad_norm 5.0 --exp_name reward_llama3-8b_ultrafb_bin_reg --n_epoch 1 
# For WARM
rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name reward --model_name llama3-8b  --dataset ultrafb_bin --wandb_enabled --wandb_project reward --global_batch_size 16 --learning_rate 7e-6 --max_grad_norm 5.0 --exp_name reward_llama3-8b_ultrafb_bin_M1 --seed 23 --n_examples 9700
rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name reward --model_name llama3-8b  --dataset ultrafb_bin --wandb_enabled --wandb_project reward --global_batch_size 16 --learning_rate 6e-6 --max_grad_norm 5.0 --exp_name reward_llama3-8b_ultrafb_bin_M2 --seed 24 --n_examples 14300
rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name reward --model_name llama3-8b  --dataset ultrafb_bin --wandb_enabled --wandb_project reward --global_batch_size 16 --learning_rate 5e-6 --max_grad_norm 5.0 --exp_name reward_llama3-8b_ultrafb_bin_M3 --seed 25 --n_examples 19200
rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name reward --model_name llama3-8b  --dataset ultrafb_bin --wandb_enabled --wandb_project reward --global_batch_size 16 --learning_rate 4e-6 --max_grad_norm 5.0 --exp_name reward_llama3-8b_ultrafb_bin_M4 --seed 26 --n_examples 24000
rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name reward --model_name llama3-8b  --dataset ultrafb_bin --wandb_enabled --wandb_project reward --global_batch_size 16 --learning_rate 3e-6 --max_grad_norm 5.0 --exp_name reward_llama3-8b_ultrafb_bin_M5 --seed 27 --n_examples 28800
# For ODIN
rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name reward_odin --model_name llama3-8b  --dataset ultrafb_bin --wandb_enabled --wandb_project reward --global_batch_size 16 --learning_rate 5e-6 --reward_odin --max_grad_norm 5.0 --exp_name reward_llama3-8b_ultrafb_bin_odin --n_epoch 1 


#############generate references and calculate reward################
rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name gen_refs --model_name llama3-8b --dataset ultrafb_bin --global_batch_size 32 --policy_path /data/models/sft_llama3-8b_ultrafb_bin --policy_tag latest_hf --reward_path /data/models/reward_llama3-8b_ultrafb_bin --reward_tag latest_hf --n_epoch 1 
python utils.py


#######ppo########
#Lab1&Lab2
rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ppo --model_name llama3-8b --dataset ultrafb_bin --wandb_enabled --wandb_project ppo --global_batch_size 40 --learning_rate 3e-7  --critic_lr 5e-6 --max_grad_norm 5.0  --policy_path /data/models/sft_llama3-8b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_llama3-8b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_llama3-8b_ultrafb_bin     --reward_tag latest_hf  --critic_path /data/models/reward_llama3-8b_ultrafb_bin         --critic_tag latest_hf  --exp_name ppo_llama3-8b_ultrafb_bin_vanilla --intermediate_checkpoints --n_epochs 1 
rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ppo --model_name llama3-8b --dataset ultrafb_bin --wandb_enabled --wandb_project ppo --global_batch_size 40 --learning_rate 3e-7  --critic_lr 5e-6 --max_grad_norm 5.0  --policy_path /data/models/sft_llama3-8b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_llama3-8b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_llama3-8b_ultrafb_bin_reg --reward_tag latest_hf  --critic_path /data/models/reward_llama3-8b_ultrafb_bin_reg     --critic_tag latest_hf  --exp_name ppo_llama3-8b_ultrafb_bin_reg --intermediate_checkpoints --n_epochs 1 
rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ppo --model_name llama3-8b --dataset ultrafb_bin --wandb_enabled --wandb_project ppo --global_batch_size 40 --learning_rate 3e-7  --critic_lr 5e-6 --max_grad_norm 5.0  --policy_path /data/models/sft_llama3-8b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_llama3-8b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_llama3-8b_ultrafb_bin     --reward_tag latest_hf  --critic_path /data/models/reward_llama3-8b_ultrafb_bin         --critic_tag latest_hf  --reward_meanstd  --exp_name ppo_llama3-8b_ultrafb_bin_meanstd  --intermediate_checkpoints --n_epochs 1 
rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ppo --model_name llama3-8b --dataset ultrafb_bin --wandb_enabled --wandb_project ppo --global_batch_size 40 --learning_rate 3e-7  --critic_lr 5e-6 --max_grad_norm 5.0  --policy_path /data/models/sft_llama3-8b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_llama3-8b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_llama3-8b_ultrafb_bin     --reward_tag latest_hf  --critic_path /data/models/reward_llama3-8b_ultrafb_bin         --critic_tag latest_hf  --reward_clipping  --exp_name ppo_llama3-8b_ultrafb_bin_clip  --intermediate_checkpoints --n_epochs 1
rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ppo --model_name llama3-8b --dataset ultrafb_bin --wandb_enabled --wandb_project ppo --global_batch_size 40 --learning_rate 3e-7  --critic_lr 5e-6 --max_grad_norm 5.0  --policy_path /data/models/sft_llama3-8b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_llama3-8b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_llama3-8b_ultrafb_bin     --reward_tag latest_hf  --critic_path /data/models/reward_llama3-8b_ultrafb_bin         --critic_tag latest_hf  --reward_minmax  --exp_name ppo_llama3-8b_ultrafb_bin_minmax  --intermediate_checkpoints --n_epochs 1
rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ppo --model_name llama3-8b --dataset ultrafb_bin --wandb_enabled --wandb_project ppo --global_batch_size 40 --learning_rate 3e-7  --critic_lr 5e-6 --max_grad_norm 5.0  --policy_path /data/models/sft_llama3-8b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_llama3-8b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_llama3-8b_ultrafb_bin     --reward_tag latest_hf  --critic_path /data/models/reward_llama3-8b_ultrafb_bin         --critic_tag latest_hf  --reward_lsc  --exp_name ppo_llama3-8b_ultrafb_bin_lsc  --intermediate_checkpoints --n_epochs 1 
rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ppo --model_name llama3-8b --dataset ultrafb_bin --wandb_enabled --wandb_project ppo --global_batch_size 40 --learning_rate 3e-7  --critic_lr 5e-6 --max_grad_norm 5.0  --policy_path /data/models/sft_llama3-8b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_llama3-8b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_llama3-8b_ultrafb_bin     --reward_tag latest_hf  --critic_path /data/models/reward_llama3-8b_ultrafb_bin         --critic_tag latest_hf  --reward_sigmoid  --exp_name ppo_llama3-8b_ultrafb_bin_sigmoid  --intermediate_checkpoints --n_epochs 1 
rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ppo --model_name llama3-8b --dataset ultrafb_bin --wandb_enabled --wandb_project ppo --global_batch_size 40 --learning_rate 3e-7  --critic_lr 5e-6 --max_grad_norm 5.0  --policy_path /data/models/sft_llama3-8b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_llama3-8b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_llama3-8b_ultrafb_bin     --reward_tag latest_hf  --critic_path /data/models/reward_llama3-8b_ultrafb_bin         --critic_tag latest_hf  --reward_par  --exp_name ppo_llama3-8b_ultrafb_bin_par  --intermediate_checkpoints --n_epochs 1 
rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ppo --model_name llama3-8b --dataset ultrafb_bin --wandb_enabled --wandb_project ppo --global_batch_size 32 --learning_rate 3e-7  --critic_lr 5e-6 --max_grad_norm 5.0  --policy_path /data/models/sft_llama3-8b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_llama3-8b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_llama3-8b_ultrafb_bin_WARM    --reward_tag latest_hf  --critic_path /data/models/reward_llama3-8b_ultrafb_bin_WARM    --critic_tag latest_hf  --exp_name ppo_llama3-8b_ultrafb_bin_WARM --intermediate_checkpoints --n_epochs 1 
rlaunch --gpu=8 --cpu=100 --replica=1 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ppo --model_name llama3-8b --dataset ultrafb_bin --wandb_enabled --wandb_project ppo --global_batch_size 40 --learning_rate 3e-7  --critic_lr 5e-6 --max_grad_norm 5.0  --policy_path /data/models/sft_llama3-8b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_llama3-8b_ultrafb_bin --reference_tag latest_hf --reward_path /data/models/reward_llama3-8b_ultrafb_bin_odin    --reward_tag latest_hf  --critic_path /data/models/reward_llama3-8b_ultrafb_bin_odin    --critic_tag latest_hf  --reward_odin --exp_name ppo_llama3-8b_ultrafb_bin_ODIN --intermediate_checkpoints --n_epochs 1 

#Lab3

####dpo###
##offline
rlaunch --gpu=8 --cpu=100 --replica=2 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name dpo --model_name llama3-8b  --dataset ultrafb_bin --wandb_enabled --wandb_project xpo --global_batch_size 32 --learning_rate 3e-7 --max_grad_norm 5.0  --policy_path /data/models/sft_llama3-8b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_llama3-8b_ultrafb_bin  --reference_tag latest_hf --reward_path /data/models/reward_llama3-8b_ultrafb_bin --reward_tag latest_hf --exp_name dpo_llama3-8b_ultrafb_bin_offline --n_epochs 1  --sample_ontest

##online
rlaunch --gpu=8 --cpu=100 --replica=2 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name dpo --model_name llama3-8b  --dataset ultrafb_bin --wandb_enabled --wandb_project xpo --global_batch_size 32 --learning_rate 3e-7  --max_grad_norm 5.0  --policy_path /data/models/sft_llama3-8b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_llama3-8b_ultrafb_bin  --reference_tag latest_hf --reward_path /data/models/reward_llama3-8b_ultrafb_bin --reward_tag latest_hf  --online --exp_name dpo_llama3-8b_ultrafb_bin_online_vanilla  --intermediate_checkpoints --n_epochs 1
rlaunch --gpu=8 --cpu=100 --replica=2 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name dpo --model_name llama3-8b  --dataset ultrafb_bin --wandb_enabled --wandb_project xpo --global_batch_size 32 --learning_rate 3e-7  --max_grad_norm 5.0  --policy_path /data/models/sft_llama3-8b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_llama3-8b_ultrafb_bin  --reference_tag latest_hf --reward_path /data/models/reward_llama3-8b_ultrafb_bin --reward_tag latest_hf  --online --reward_discrete --reward_discrete_maxref 5 --exp_name dpo_llama3-8b_ultrafb_bin_online_discrete --intermediate_checkpoints --n_epochs 1

####ipo###
##offline
rlaunch --gpu=8 --cpu=100 --replica=2 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ipo --model_name llama3-8b  --dataset ultrafb_bin --wandb_enabled --wandb_project xpo --global_batch_size 32 --learning_rate 3e-7 --max_grad_norm 5.0  --policy_path /data/models/sft_llama3-8b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_llama3-8b_ultrafb_bin  --reference_tag latest_hf --reward_path /data/models/reward_llama3-8b_ultrafb_bin --reward_tag latest_hf --exp_name ipo_llama3-8b_ultrafb_bin_offline --n_epochs 1  --sample_ontest

##online
rlaunch --gpu=8 --cpu=100 --replica=2 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ipo --model_name llama3-8b  --dataset ultrafb_bin --wandb_enabled --wandb_project xpo --global_batch_size 32 --learning_rate 3e-7  --max_grad_norm 5.0  --policy_path /data/models/sft_llama3-8b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_llama3-8b_ultrafb_bin  --reference_tag latest_hf --reward_path /data/models/reward_llama3-8b_ultrafb_bin --reward_tag latest_hf  --online --exp_name ipo_llama3-8b_ultrafb_bin_online_vanilla  --intermediate_checkpoints --n_epochs 1
rlaunch --gpu=8 --cpu=100 --replica=2 --memory=800000 --set-env NCCL_PXN_DISABLE=1 --charged-group=stepchat --private-machine=group --positive-tags feature/gpfs=yes  --custom-resources mellanox.com/mlnx_rdma=1 --custom-resources rdma/mlnx_shared=8 -- /mnt/shared-storage/tenant/jobutils/scripts/smartrun train.py --loss_name ipo --model_name llama3-8b  --dataset ultrafb_bin --wandb_enabled --wandb_project xpo --global_batch_size 32 --learning_rate 3e-7  --max_grad_norm 5.0  --policy_path /data/models/sft_llama3-8b_ultrafb_bin --policy_tag latest_hf --reference_path /data/models/sft_llama3-8b_ultrafb_bin  --reference_tag latest_hf --reward_path /data/models/reward_llama3-8b_ultrafb_bin --reward_tag latest_hf  --online --reward_discrete --reward_discrete_maxref 5 --exp_name ipo_llama3-8b_ultrafb_bin_online_discrete --intermediate_checkpoints --n_epochs 1